### ISSUE TITLE
🚀 [Story] Partial liquidity removal from the pool

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#223]
As an end user, I want to be able to **remove as much liquidity as I want** from an existing pool that I participate in.

- I should be able to click on a button in the liquidity pools list to remove my liquidity from the pool where I participate.
- I should be able to choose how much liquidity I want to withdraw - 20%, 80% etc. 
- I should be informed on what is the maximum I can withdraw. 
- I should be able to overview and confirm my liquidity withdrawal.
- I should be informed about my updated liquidity share status in the pool.
- I should return to the liquidity pool list with the updated information.

### 😳 **Unhappy paths:** 

- I should not be able to remove liquidity from the pool where I don’t participate.
- I should not be able to remove more than the maximum amount allowed from the pool.
- I should be able to reject liquidity removal transactions. 
- I should not be able to remove liquidity if I cancel transaction from the wallet. 

### 📌 **Subtasks:** 📄

- [x] Design this feature
- [x] Add partial liquidity field 
- [x] Implement withdraw function
- [x] Wire the flow and test

**Comment by gagi13** [comment]
Update: create pool request by the end of day
