### ISSUE TITLE
Network switcher (choosing parachain)

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#224]
As an end user, I want to be able to switch between Westmint and Rococo network to use dotACP.

- I should be able to click on a button to change the network on which dotACP is running. 
- I should be able to overview and confirm my switching the network.

<img width="808" alt="Screenshot 2023-11-27 at 12 55 15" src="https://github.com/MVPWorkshop/dot-acp-ui/assets/101146655/e3e6a315-2c42-4b5f-8bd8-dc7ab2f38a50">
<img width="1024" alt="Screenshot 2023-11-27 at 12 56 44" src="https://github.com/MVPWorkshop/dot-acp-ui/assets/101146655/25d01110-060b-4144-8042-200d72cf8069">

### 📌 **Subtasks:** 📄
- [x] Create network switcher 
- [x] Implement switching network functionality 
- [x] Wire the flow and test
