### ISSUE TITLE
🚀 [Story] Nice to have features

### ISSUE THREAD

**Issue by gagi13** [MVPWorkshop/dot-acp-ui#48]
### 📌 **Subtasks:** 📄

**Zero Tier** (going together with MVP, delivered until 31st Oct)

- [x] #94 
- [x] #167 
- [x] #207 
- [x] #193
- [x] #168 

**First Tier**
- [x] #40 
- [x] #223 
- [x] #164 (1)
- [x] #165 (1)
- [x] #166 (1)
- [x] Edit slippage (swap, add, remove liquidity, create LP)
- [x] If a pool exists add a liquidity to it in Pool Creation Flow
- [ ] #169 (2) (not supported by the pallet)
- [x] #224 (2)
- [ ] #170 (not supported by the pallet)

**Second Tier**

- [x] #225
- [x] Disconnect wallet
- [x] #226 (2)
- [x] #227
- [x] #228 (2)

**Third Tier** 

- [x] #229
- [x] #230 (2)
- [x] #231
